"""add remaining tables

Revision ID: eff11535c68a
Revises: 3a92e031fe53
Create Date: 2026-01-18 00:15:35.332958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff11535c68a'
down_revision: Union[str, Sequence[str], None] = '3a92e031fe53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diet_meals',
    sa.Column('diet_meals_id', sa.UUID(), nullable=False),
    sa.Column('diet_id', sa.UUID(), nullable=True),
    sa.Column('meal_name', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['diet_id'], ['diet_library.diet_library_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('diet_meals_id')
    )
    op.create_table('trainee_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('trainer_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['trainers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trainee_id', sa.UUID(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_trainee_diet',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trainee_id', sa.UUID(), nullable=True),
    sa.Column('day_name', sa.String(), nullable=False),
    sa.Column('diet_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['diet_id'], ['diet_library.diet_library_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_trainee_weekly_workouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trainee_id', sa.UUID(), nullable=True),
    sa.Column('day_name', sa.String(), nullable=False),
    sa.Column('workout_template_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_template_id'], ['workout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diet_items',
    sa.Column('diet_items_id', sa.UUID(), nullable=False),
    sa.Column('meal_id', sa.UUID(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=False),
    sa.Column('time_slot', sa.Time(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['diet_meals.diet_meals_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('diet_items_id')
    )
    op.create_table('group_monthly_workouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('date_day', sa.Integer(), nullable=False),
    sa.Column('workout_template_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['trainee_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_template_id'], ['workout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_weekly_diet',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('day_name', sa.String(), nullable=False),
    sa.Column('diet_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['diet_id'], ['diet_library.diet_library_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['trainee_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_weekly_workouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('day_name', sa.String(), nullable=False),
    sa.Column('workout_template_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['trainee_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_template_id'], ['workout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainee_plan',
    sa.Column('trainee_plan_id', sa.UUID(), nullable=False),
    sa.Column('trainee_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('plan_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('active_status', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['membership_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trainee_plan_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainee_plan')
    op.drop_table('group_weekly_workouts')
    op.drop_table('group_weekly_diet')
    op.drop_table('group_monthly_workouts')
    op.drop_table('diet_items')
    op.drop_table('custom_trainee_weekly_workouts')
    op.drop_table('custom_trainee_diet')
    op.drop_table('attendance')
    op.drop_table('workout_templates')
    op.drop_table('trainee_groups')
    op.drop_table('diet_meals')
    op.drop_table('payments')
    # ### end Alembic commands ###
