"""baseline

Revision ID: 16af5a98d4f8
Revises: 
Create Date: 2026-06-12 17:25:53.068319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types


# revision identifiers, used by Alembic.
revision: str = '16af5a98d4f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('branch_name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_number', sa.Text(), nullable=True),
    sa.Column('owner_id', app.db.types.GUID(), nullable=False),
    sa.Column('allow_trainer_renewal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    # owner_id FK added after profiles exists — branches<->profiles are circular
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('profile_id', app.db.types.GUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_mode', sa.Enum('Cash', 'Card', 'UPI', name='payment_mode_enum'), nullable=False),
    sa.Column('payment_status', sa.Enum('Completed', 'Pending', 'Failed', name='payment_status_enum'), nullable=False),
    sa.Column('receipt_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('profile_image', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('Admin', 'Owner', 'Receptionist', 'Trainer', 'Trainee', name='userroleenum'), nullable=False),
    sa.Column('branch_id', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # close the branches<->profiles cycle now that both tables exist
    op.create_foreign_key(
        'branches_owner_id_fkey', 'branches', 'profiles',
        ['owner_id'], ['id'], ondelete='RESTRICT'
    )
    op.create_table('sleep_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trainee_id', sa.UUID(), nullable=False),
    sa.Column('sleep_date', sa.Date(), nullable=False),
    sa.Column('sleep_start', sa.Time(), nullable=True),
    sa.Column('sleep_end', sa.Time(), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('total_sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('woke_up_count', sa.Integer(), nullable=True),
    sa.Column('deep_sleep_rating', sa.Integer(), nullable=True),
    sa.Column('sleep_quality_notes', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diet_library',
    sa.Column('diet_library_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_by', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('diet_library_id')
    )
    op.create_table('membership_plans',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('branch_id', app.db.types.GUID(), nullable=True),
    sa.Column('plan_name', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainers',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diet_meals',
    sa.Column('diet_meals_id', app.db.types.GUID(), nullable=False),
    sa.Column('diet_id', app.db.types.GUID(), nullable=True),
    sa.Column('meal_name', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['diet_id'], ['diet_library.diet_library_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('diet_meals_id')
    )
    op.create_table('trainee_groups',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('trainer_id', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainees',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('trainer_id', app.db.types.GUID(), nullable=True),
    sa.Column('bmi', sa.Numeric(), nullable=True),
    sa.Column('weight', sa.Numeric(), nullable=True),
    sa.Column('height', sa.Numeric(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('last_absent_email_sent', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainer_attendance',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('trainer_id', app.db.types.GUID(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('is_present', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_templates',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('creator_id', app.db.types.GUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['trainers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('trainee_id', app.db.types.GUID(), nullable=True),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('is_present', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_trainee_diet',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('trainee_id', app.db.types.GUID(), nullable=True),
    sa.Column('day_name', sa.String(), nullable=False),
    sa.Column('diet_id', app.db.types.GUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['diet_id'], ['diet_library.diet_library_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_trainee_weekly_workouts',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('trainee_id', app.db.types.GUID(), nullable=True),
    sa.Column('day_name', sa.String(), nullable=False),
    sa.Column('workout_template_id', app.db.types.GUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_template_id'], ['workout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_nutrition',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('trainee_id', app.db.types.GUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quality_rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diet_items',
    sa.Column('diet_items_id', app.db.types.GUID(), nullable=False),
    sa.Column('meal_id', app.db.types.GUID(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=False),
    sa.Column('time_slot', sa.Time(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fats', sa.Float(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['diet_meals.diet_meals_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('diet_items_id')
    )
    op.create_table('group_monthly_workouts',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('group_id', app.db.types.GUID(), nullable=True),
    sa.Column('date_day', sa.Integer(), nullable=False),
    sa.Column('workout_template_id', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['trainee_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_template_id'], ['workout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_weekly_diet',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('group_id', app.db.types.GUID(), nullable=True),
    sa.Column('day_name', sa.String(), nullable=False),
    sa.Column('diet_id', app.db.types.GUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['diet_id'], ['diet_library.diet_library_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['trainee_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_weekly_workouts',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('group_id', app.db.types.GUID(), nullable=True),
    sa.Column('day_name', sa.String(), nullable=False),
    sa.Column('workout_template_id', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['trainee_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_template_id'], ['workout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrient_goals',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('trainee_id', app.db.types.GUID(), nullable=False),
    sa.Column('daily_calories', sa.Float(), nullable=True),
    sa.Column('daily_protein', sa.Float(), nullable=True),
    sa.Column('daily_carbs', sa.Float(), nullable=True),
    sa.Column('daily_fats', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainee_id')
    )
    op.create_table('nutrition_logs',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('trainee_id', app.db.types.GUID(), nullable=False),
    sa.Column('log_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meal_name', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fats', sa.Float(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_tokens',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('trainee_id', app.db.types.GUID(), nullable=False),
    sa.Column('push_token', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainee_id')
    )
    op.create_table('sleep_reminders',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('trainee_id', app.db.types.GUID(), nullable=False),
    sa.Column('bedtime', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainee_group_members',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('trainee_id', app.db.types.GUID(), nullable=True),
    sa.Column('group_id', app.db.types.GUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['trainee_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_reminders',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('trainee_id', app.db.types.GUID(), nullable=False),
    sa.Column('reminder_time', sa.Time(), nullable=False),
    sa.Column('days_of_week', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_logs',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('trainee_id', app.db.types.GUID(), nullable=False),
    sa.Column('attendance_id', app.db.types.GUID(), nullable=True),
    sa.Column('workout_template_id', app.db.types.GUID(), nullable=True),
    sa.Column('workout_date', sa.Date(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('auto_tracked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_template_id'], ['workout_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('branches_owner_id_fkey', 'branches', type_='foreignkey')
    op.drop_table('workout_logs')
    op.drop_table('workout_reminders')
    op.drop_table('trainee_group_members')
    op.drop_table('sleep_reminders')
    op.drop_table('push_tokens')
    op.drop_table('nutrition_logs')
    op.drop_table('nutrient_goals')
    op.drop_table('group_weekly_workouts')
    op.drop_table('group_weekly_diet')
    op.drop_table('group_monthly_workouts')
    op.drop_table('diet_items')
    op.drop_table('daily_nutrition')
    op.drop_table('custom_trainee_weekly_workouts')
    op.drop_table('custom_trainee_diet')
    op.drop_table('attendance')
    op.drop_table('workout_templates')
    op.drop_table('trainer_attendance')
    op.drop_table('trainees')
    op.drop_table('trainee_groups')
    op.drop_table('diet_meals')
    op.drop_table('trainers')
    op.drop_table('membership_plans')
    op.drop_table('diet_library')
    op.drop_table('sleep_logs')
    op.drop_table('profiles')
    op.drop_table('payments')
    op.drop_table('branches')
    # ### end Alembic commands ###
